const YOUTUBE_RESOURCES = [
  {
    topic: 'C Masterclass Tutorial 1',
    channel: 'Coding Boss',
    url: 'https://youtu.be/Wy0WCzVsTXA?si=-AiAModTGau5xSI3',
    thumbnail: '🎯',
    duration: 'Video 1',
    description: 'Complete C course from scratch — perfect for absolute beginners',
    level: 'Beginner',
    color: 'bg-red-50 border-red-200 text-red-900',
    badge: 'bg-red-100 text-red-700',
    locked: false,
  },
  {
    topic: 'C Masterclass Tutorial 2',
    channel: 'Coding Boss',
    url: 'https://youtu.be/lRzg5XZwzR4?si=lfvNjQi4c59VnaxX',
    thumbnail: '🏗️',
    duration: 'Video 2',
    description: 'Master C concepts with real examples',
    level: 'Intermediate',
    color: 'bg-blue-50 border-blue-200 text-blue-900',
    badge: 'bg-blue-100 text-blue-700',
    locked: false,
  },
  {
    topic: 'C Masterclass Tutorial 3',
    channel: 'Coding Boss',
    url: 'https://youtu.be/cTyAQyfJ7ds?si=0GMdSemoE2Pea3Io',
    thumbnail: '📊',
    duration: 'Video 3',
    description: 'Deep dive into pointers and memory management',
    level: 'Intermediate',
    color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
    badge: 'bg-emerald-100 text-emerald-700',
    locked: false,
  },
  {
    topic: 'C Masterclass Tutorial 4',
    channel: 'Coding Boss',
    url: 'https://youtu.be/wRr288fC21I?si=sHQOC34jErLeoDJz',
    thumbnail: '🛡️',
    duration: 'Video 4',
    description: 'Learn dynamic memory allocation properly',
    level: 'Advanced',
    color: 'bg-purple-50 border-purple-200 text-purple-900',
    badge: 'bg-purple-100 text-purple-700',
    locked: false,
  },
  {
    topic: 'Advanced Data Structures in C',
    channel: 'Coding Boss Max',
    url: '#',
    thumbnail: '🔒',
    duration: 'Premium',
    description: 'Premium content: Master trees, graphs, and advanced C data structures',
    level: 'Premium Content',
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    badge: 'bg-amber-100 text-amber-700',
    locked: true,
  },
  {
    topic: 'File Handling Deep Dive',
    channel: 'Coding Boss Max',
    url: '#',
    thumbnail: '🔒',
    duration: 'Premium',
    description: 'Premium content: Master file operations like a pro',
    level: 'Premium Content',
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    badge: 'bg-amber-100 text-amber-700',
    locked: true,
  },
  {
    topic: 'C Networking and Sockets',
    channel: 'Coding Boss Max',
    url: '#',
    thumbnail: '🔒',
    duration: 'Premium',
    description: 'Premium content: Network programming concepts in C',
    level: 'Premium Content',
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    badge: 'bg-amber-100 text-amber-700',
    locked: true,
  },
  {
    topic: 'C Multithreading Masterclass',
    channel: 'Coding Boss Max',
    url: '#',
    thumbnail: '🔒',
    duration: 'Premium',
    description: 'Premium content: Parallel programming safely in C',
    level: 'Premium Content',
    color: 'bg-amber-50 border-amber-200 text-amber-900',
    badge: 'bg-amber-100 text-amber-700',
    locked: true,
  },
];